import { WebsiteAudit } from '../src/types';

export const SEED_PROFESSIONAL_AUDITS: WebsiteAudit[] = [
  // 1. MICROSOFT CORPORATION
  {
    id: 'aud-seed-microsoft',
    websiteName: 'Microsoft Corporation',
    domain: 'microsoft.com',
    rootUrl: 'https://www.microsoft.com',
    status: 'completed',
    totalUrlsDiscovered: 2840,
    analyzedUrlsCount: 6,
    averageScores: {
      seo: 96,
      aeo: 92,
      aio: 94,
      geo: 91,
      eeat: 98,
      overall: 94,
    },
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 1.9).toISOString(),
    globalAiRecommendations: [
      '[AEO Optimization]: Expand direct conversational FAQ markup across Copilot and Azure product subdomains to capture multi-turn Perplexity queries.',
      '[AIO Machine Readability]: Ensure all secondary documentation pages include structured TechArticle and SoftwareApplication JSON-LD schemas.',
      '[GEO & Citation]: Standardize quantitative productivity statistics in cloud case studies to boost generative citation rates in ChatGPT and Copilot.',
      '[E-E-A-T Excellence]: Maintain global SOC2, ISO-27001, and GDPR compliance badges prominently across developer portal footers.',
    ],
    topFindings: [
      {
        id: 'f-ms-01',
        category: 'eeat',
        severity: 'good',
        title: 'Verifiable Enterprise Trust & Security Badges',
        evidence: 'SSL/TLS encrypted, SOC2 Type II, ISO-27001, and GDPR compliance badges verified.',
        explanation: 'Fulfills Google Quality Rater guidelines for top-tier enterprise trustworthiness.',
        solution: 'Maintain sitewide HTTPS and clear legal links.',
      },
      {
        id: 'f-ms-02',
        category: 'aio',
        severity: 'good',
        title: 'Structured Organization & SoftwareApplication Schema',
        evidence: 'Detected valid Organization, WebSite, and SoftwareApplication JSON-LD schemas.',
        explanation: 'Enables Google AI Overviews and Knowledge Graphs to parse product entities accurately.',
        solution: 'Ensure all software releases feature updated version tags in schema.',
      },
      {
        id: 'f-ms-03',
        category: 'aeo',
        severity: 'warning',
        title: 'Deep Subdomain FAQ Markup Consistency',
        evidence: 'Some support subpaths lack FAQPage JSON-LD schema despite containing Q&A sections.',
        explanation: 'Answer Engines prefer explicit FAQPage markup to cite verbatim answers in voice search.',
        solution: 'Deploy automated FAQPage schema across all customer support articles.',
      },
      {
        id: 'f-ms-04',
        category: 'seo',
        severity: 'good',
        title: 'Optimized Title & Meta Description Tags',
        evidence: 'Title length is 52 characters; Meta description is 148 characters.',
        explanation: 'Optimal snippet rendering in SERPs without truncation.',
        solution: 'Continue monitoring SERP click-through rates.',
      },
    ],
    urlReports: [
      {
        id: 'rep-ms-home',
        url: 'https://www.microsoft.com',
        path: '/',
        title: 'Microsoft – Cloud, Computers, Apps & Gaming',
        metaDescription: 'Explore Microsoft products and services for your home or business. Shop Surface, Microsoft 365, Xbox, Windows, Azure, and Copilot.',
        canonicalUrl: 'https://www.microsoft.com/',
        robots: 'index, follow',
        statusCode: 200,
        responseTimeMs: 142,
        wordCount: 1250,
        readingTimeMinutes: 7,
        internalLinksCount: 184,
        externalLinksCount: 32,
        imagesCount: 28,
        imagesWithoutAlt: 0,
        headings: {
          h1: ['Microsoft 365 & Copilot Solutions'],
          h2: ['For Home', 'For Business', 'Developer & Cloud', 'Latest Innovations'],
          h3: ['Surface Pro 11', 'Xbox Series X', 'Azure AI Services', 'Windows 11'],
        },
        schemaTypes: ['Organization', 'WebSite', 'Brand'],
        openGraph: {
          'og:title': 'Microsoft Official Portal',
          'og:description': 'Explore Microsoft products and enterprise AI cloud services.',
          'og:type': 'website',
        },
        twitterCard: {
          'twitter:card': 'summary_large_image',
          'twitter:site': '@Microsoft',
        },
        scores: { seo: 98, aeo: 94, aio: 96, geo: 92, eeat: 99, overall: 96 },
        findings: [
          {
            id: 'f-ms-h1',
            category: 'seo',
            severity: 'good',
            title: '100% Image Alt Text Compliance',
            evidence: 'All 28 images feature descriptive alt text.',
            explanation: 'Ensures screen reader accessibility and image search indexability.',
            solution: 'Maintain strict media upload guidelines.',
          },
        ],
        aiRecommendations: [
          'Add FAQPage schema on the main Copilot landing page to maximize voice search snippets.',
        ],
        crawledAt: new Date(Date.now() - 3600000 * 2).toISOString(),
      },
      {
        id: 'rep-ms-about',
        url: 'https://www.microsoft.com/about',
        path: '/about',
        title: 'About Microsoft – Our Mission and Story',
        metaDescription: 'Learn about Microsoft corporate mission, leadership, sustainability commitments, and career opportunities.',
        canonicalUrl: 'https://www.microsoft.com/about',
        robots: 'index, follow',
        statusCode: 200,
        responseTimeMs: 165,
        wordCount: 1820,
        readingTimeMinutes: 9,
        internalLinksCount: 92,
        externalLinksCount: 18,
        imagesCount: 14,
        imagesWithoutAlt: 0,
        headings: {
          h1: ['Empowering Every Person and Organization on the Planet'],
          h2: ['Our Mission', 'Global Impact & Sustainability', 'Leadership & Ethics'],
          h3: ['Carbon Negative by 2030', 'Responsible AI Principles'],
        },
        schemaTypes: ['Organization', 'AboutPage', 'Person'],
        openGraph: {
          'og:title': 'About Microsoft',
          'og:description': 'Our mission and global impact commitments.',
        },
        twitterCard: { 'twitter:card': 'summary' },
        scores: { seo: 96, aeo: 90, aio: 95, geo: 94, eeat: 98, overall: 95 },
        findings: [
          {
            id: 'f-ms-about-eeat',
            category: 'eeat',
            severity: 'good',
            title: 'Verified Corporate Leadership & Bio Schemas',
            evidence: 'Detailed Person and Organization schemas detected.',
            explanation: 'Strengthens E-E-A-T entity credibility.',
            solution: 'Keep leadership bios updated.',
          },
        ],
        aiRecommendations: [
          'Include explicit links to peer-reviewed sustainability whitepapers.',
        ],
        crawledAt: new Date(Date.now() - 3600000 * 2).toISOString(),
      },
    ],
  },

  // 2. APPLE INC
  {
    id: 'aud-seed-apple',
    websiteName: 'Apple Inc.',
    domain: 'apple.com',
    rootUrl: 'https://www.apple.com',
    status: 'completed',
    totalUrlsDiscovered: 3120,
    analyzedUrlsCount: 6,
    averageScores: {
      seo: 95,
      aeo: 89,
      aio: 92,
      geo: 88,
      eeat: 97,
      overall: 92,
    },
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 4.8).toISOString(),
    globalAiRecommendations: [
      '[AEO Voice Search]: Add direct Q&A summary paragraphs on Apple Support pages to improve Siri and Perplexity answer extractions.',
      '[GEO & Quotation]: Include explicit battery life benchmarks and specs tables in plain text rather than JS-rendered canvases.',
      '[AIO Machine Readability]: Expand Product and Offer JSON-LD schema properties on regional apple.com subpages.',
    ],
    topFindings: [
      {
        id: 'f-ap-01',
        category: 'seo',
        severity: 'good',
        title: 'Ultra-Fast Server Response Time & Clean DOM',
        evidence: 'Mean TTFB under 110ms with pristine semantic HTML5 markup.',
        explanation: 'Provides superior user experience and crawling efficiency.',
        solution: 'Maintain edge CDN caching performance.',
      },
      {
        id: 'f-ap-02',
        category: 'aeo',
        severity: 'warning',
        title: 'Heavy Dynamic Canvas Rendering for Technical Specs',
        evidence: 'Product spec tables rendered via client-side WebGL/JS rather than plain semantic HTML.',
        explanation: 'Can prevent simple text crawlers and voice engines from parsing raw specs directly.',
        solution: 'Provide fallback semantic HTML tables for technical specifications.',
      },
    ],
    urlReports: [
      {
        id: 'rep-ap-home',
        url: 'https://www.apple.com',
        path: '/',
        title: 'Apple – iPhone 16 Pro, iPad, Mac, Watch, and Vision Pro',
        metaDescription: 'Discover the innovative world of Apple. Shop iPhone, iPad, Mac, Apple Watch, Vision Pro, and explore accessories, entertainment, and support.',
        canonicalUrl: 'https://www.apple.com/',
        robots: 'index, follow',
        statusCode: 200,
        responseTimeMs: 110,
        wordCount: 980,
        readingTimeMinutes: 5,
        internalLinksCount: 142,
        externalLinksCount: 12,
        imagesCount: 22,
        imagesWithoutAlt: 0,
        headings: {
          h1: ['iPhone 16 Pro – Built for Apple Intelligence'],
          h2: ['MacBook Pro', 'Apple Watch Series 10', 'iPad Pro', 'Apple Vision Pro'],
          h3: ['Hello, Apple Intelligence.', 'Explore All Models'],
        },
        schemaTypes: ['Organization', 'WebSite', 'Product'],
        openGraph: {
          'og:title': 'Apple Official Site',
          'og:description': 'Discover iPhone, Mac, iPad, Watch, and Vision Pro.',
        },
        twitterCard: { 'twitter:card': 'summary_large_image' },
        scores: { seo: 97, aeo: 88, aio: 93, geo: 86, eeat: 98, overall: 92 },
        findings: [
          {
            id: 'f-ap-good-seo',
            category: 'seo',
            severity: 'good',
            title: 'High Semantic HTML Compliance',
            evidence: 'Clean usage of <header>, <nav>, <main>, <section>, and <footer>.',
            explanation: 'Allows AI web parsers to isolate main product content effortlessly.',
            solution: 'Maintain HTML5 standard.',
          },
        ],
        aiRecommendations: [
          'Incorporate FAQPage schema on product landing pages for voice assistant integration.',
        ],
        crawledAt: new Date(Date.now() - 3600000 * 5).toISOString(),
      },
    ],
  },

  // 3. WIKIPEDIA ORG
  {
    id: 'aud-seed-wikipedia',
    websiteName: 'Wikipedia – Free Knowledge Base',
    domain: 'wikipedia.org',
    rootUrl: 'https://www.wikipedia.org',
    status: 'completed',
    totalUrlsDiscovered: 15400,
    analyzedUrlsCount: 6,
    averageScores: {
      seo: 98,
      aeo: 96,
      aio: 97,
      geo: 99,
      eeat: 95,
      overall: 97,
    },
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 11.8).toISOString(),
    globalAiRecommendations: [
      '[AEO & GEO Benchmark]: Wikipedia is the gold standard for Answer Engine citation density. Maintain clear first-sentence definition paragraphs under H2 headers.',
      '[AIO Citation Graph]: Expand structured JSON-LD Person and Event schemas across historical entries.',
    ],
    topFindings: [
      {
        id: 'f-wiki-01',
        category: 'geo',
        severity: 'good',
        title: 'World-Class Quotability & Outbound Reference Citations',
        evidence: 'Over 45 outbound citations and verifiable footnotes per article.',
        explanation: 'Generative search engines (ChatGPT, Perplexity) rank Wikipedia articles #1 for factual synthesis.',
        solution: 'Maintain strict citations policy.',
      },
      {
        id: 'f-wiki-02',
        category: 'aeo',
        severity: 'good',
        title: 'Pithy 40-Word Opening Definitions',
        evidence: 'Every article begins with a concise 2-sentence definition before deep sections.',
        explanation: 'Perfect format for Perplexity and Google AI Overviews.',
        solution: 'Preserve lead paragraph concise structure.',
      },
    ],
    urlReports: [
      {
        id: 'rep-wiki-home',
        url: 'https://www.wikipedia.org',
        path: '/',
        title: 'Wikipedia, the free encyclopedia',
        metaDescription: 'Wikipedia is a free online encyclopedia, created and edited by volunteers around the world and hosted by the Wikimedia Foundation.',
        canonicalUrl: 'https://www.wikipedia.org/',
        robots: 'index, follow',
        statusCode: 200,
        responseTimeMs: 85,
        wordCount: 1450,
        readingTimeMinutes: 7,
        internalLinksCount: 310,
        externalLinksCount: 45,
        imagesCount: 12,
        imagesWithoutAlt: 0,
        headings: {
          h1: ['Wikipedia – The Free Encyclopedia'],
          h2: ['1,000,000+ Articles', '100,000+ Articles', 'Other Projects'],
          h3: ['English', 'Español', 'Français', 'Deutsch', 'Urdu'],
        },
        schemaTypes: ['WebSite', 'Organization'],
        openGraph: {
          'og:title': 'Wikipedia',
          'og:description': 'The free online encyclopedia.',
        },
        twitterCard: { 'twitter:card': 'summary' },
        scores: { seo: 99, aeo: 96, aio: 98, geo: 99, eeat: 96, overall: 98 },
        findings: [
          {
            id: 'f-wiki-good',
            category: 'geo',
            severity: 'good',
            title: 'High Density of Verified External References',
            evidence: 'Contains extensive scholarly footnotes and citations.',
            explanation: 'Acts as primary authority in AI Knowledge Graphs.',
            solution: 'Continue updating reference links.',
          },
        ],
        aiRecommendations: [
          'Add explicit Organization JSON-LD logo and contact schema.',
        ],
        crawledAt: new Date(Date.now() - 3600000 * 12).toISOString(),
      },
    ],
  },

  // 4. SHOPIFY E-COMMERCE
  {
    id: 'aud-seed-shopify',
    websiteName: 'Shopify E-Commerce Platform',
    domain: 'shopify.com',
    rootUrl: 'https://www.shopify.com',
    status: 'completed',
    totalUrlsDiscovered: 1850,
    analyzedUrlsCount: 6,
    averageScores: {
      seo: 94,
      aeo: 91,
      aio: 93,
      geo: 89,
      eeat: 95,
      overall: 92,
    },
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 23.8).toISOString(),
    globalAiRecommendations: [
      '[AEO & Local Commerce]: Standardize FAQPage schema on pricing and feature pages to capture conversational "How to start online store" queries.',
      '[AIO Machine Readability]: Incorporate SoftwareApplication JSON-LD schema with exact pricing tiers and user rating metrics.',
    ],
    topFindings: [
      {
        id: 'f-sh-01',
        category: 'seo',
        severity: 'good',
        title: 'High-Intent Title & Meta Tag Optimization',
        evidence: 'Titles and descriptions match commercial e-commerce intent precisely.',
        explanation: 'Drives high click-through rates from organic search.',
        solution: 'Maintain current SEO keyword strategy.',
      },
    ],
    urlReports: [
      {
        id: 'rep-sh-home',
        url: 'https://www.shopify.com',
        path: '/',
        title: 'Start and grow your e-commerce business – 3-Day Free Trial – Shopify',
        metaDescription: 'Try Shopify free and start a business or grow an existing one. Get more than a commerce platform with tools to power your business from start to scale.',
        canonicalUrl: 'https://www.shopify.com/',
        robots: 'index, follow',
        statusCode: 200,
        responseTimeMs: 135,
        wordCount: 1650,
        readingTimeMinutes: 8,
        internalLinksCount: 165,
        externalLinksCount: 22,
        imagesCount: 18,
        imagesWithoutAlt: 0,
        headings: {
          h1: ['The global commerce platform built for all businesses'],
          h2: ['Build your store', 'Sell everywhere', 'Market your business', 'Manage everything'],
          h3: ['Online Store Builder', 'Point of Sale (POS)', 'Shop Pay Checkout'],
        },
        schemaTypes: ['Organization', 'SoftwareApplication', 'WebSite'],
        openGraph: {
          'og:title': 'Shopify Commerce Platform',
          'og:description': 'Start and grow your business with Shopify.',
        },
        twitterCard: { 'twitter:card': 'summary_large_image' },
        scores: { seo: 95, aeo: 90, aio: 94, geo: 88, eeat: 96, overall: 93 },
        findings: [
          {
            id: 'f-sh-good',
            category: 'aio',
            severity: 'good',
            title: 'Complete SoftwareApplication Schema Active',
            evidence: 'Valid SoftwareApplication and Organization schema parsed.',
            explanation: 'Helps AI Overviews display trial options and feature sets.',
            solution: 'Update schema on new product announcements.',
          },
        ],
        aiRecommendations: [
          'Add explicit FAQPage markup on POS and international pricing sections.',
        ],
        crawledAt: new Date(Date.now() - 3600000 * 24).toISOString(),
      },
    ],
  },

  // 5. ADOBE SYSTEMS
  {
    id: 'aud-seed-adobe',
    websiteName: 'Adobe Systems',
    domain: 'adobe.com',
    rootUrl: 'https://www.adobe.com',
    status: 'completed',
    totalUrlsDiscovered: 2100,
    analyzedUrlsCount: 6,
    averageScores: {
      seo: 93,
      aeo: 88,
      aio: 91,
      geo: 87,
      eeat: 96,
      overall: 91,
    },
    createdAt: new Date(Date.now() - 3600000 * 36).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 35.8).toISOString(),
    globalAiRecommendations: [
      '[AEO Optimization]: Integrate conversational Q&A headers on Adobe Express and Photoshop tutorials.',
      '[GEO Quotable Metrics]: Highlight Firefly AI generation speed benchmarks in readable plain text.',
    ],
    topFindings: [
      {
        id: 'f-ad-01',
        category: 'eeat',
        severity: 'good',
        title: 'Verified Corporate Trust Signals',
        evidence: 'Complete legal footer, HTTPS, and Privacy Trust Center links verified.',
        explanation: 'High E-E-A-T rating across search engines.',
        solution: 'Maintain global compliance.',
      },
    ],
    urlReports: [
      {
        id: 'rep-ad-home',
        url: 'https://www.adobe.com',
        path: '/',
        title: 'Adobe: Creative, marketing and document management solutions',
        metaDescription: 'Adobe is changing the world through digital experiences. We help our customers create, deliver and optimize content and applications.',
        canonicalUrl: 'https://www.adobe.com/',
        robots: 'index, follow',
        statusCode: 200,
        responseTimeMs: 150,
        wordCount: 1420,
        readingTimeMinutes: 7,
        internalLinksCount: 175,
        externalLinksCount: 19,
        imagesCount: 20,
        imagesWithoutAlt: 0,
        headings: {
          h1: ['Creativity for all with Adobe Creative Cloud'],
          h2: ['Photoshop', 'Acrobat PDF', 'Adobe Express', 'Creative Cloud All Apps'],
          h3: ['Generative AI in Photoshop', 'Edit PDF Online'],
        },
        schemaTypes: ['Organization', 'SoftwareApplication', 'WebSite'],
        openGraph: {
          'og:title': 'Adobe Official Portal',
          'og:description': 'Creative, marketing, and document management solutions.',
        },
        twitterCard: { 'twitter:card': 'summary_large_image' },
        scores: { seo: 94, aeo: 87, aio: 92, geo: 86, eeat: 97, overall: 91 },
        findings: [
          {
            id: 'f-ad-good',
            category: 'seo',
            severity: 'good',
            title: 'Optimal Canonical & Language Meta Tags',
            evidence: 'hreflang and canonical links properly defined.',
            explanation: 'Prevents international duplicate content issues.',
            solution: 'Maintain regional routing rules.',
          },
        ],
        aiRecommendations: [
          'Add FAQPage schema on Creative Cloud plans page.',
        ],
        crawledAt: new Date(Date.now() - 3600000 * 36).toISOString(),
      },
    ],
  },

  // 6. DARAZ PAKISTAN
  {
    id: 'aud-seed-daraz',
    websiteName: 'Daraz Pakistan E-Commerce',
    domain: 'daraz.pk',
    rootUrl: 'https://www.daraz.pk',
    status: 'completed',
    totalUrlsDiscovered: 4200,
    analyzedUrlsCount: 6,
    averageScores: {
      seo: 91,
      aeo: 86,
      aio: 89,
      geo: 84,
      eeat: 92,
      overall: 88,
    },
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 47.8).toISOString(),
    globalAiRecommendations: [
      '[AEO & Local Search]: Implement Urdu & English FAQPage JSON-LD schema across customer care and order tracking pages.',
      '[AIO Product Schema]: Ensure all product listing cards feature valid AggregateRating and Offer schema attributes.',
      '[GEO Local Quotability]: Publish transparent delivery timelines and buyer protection metrics in plain text.',
    ],
    topFindings: [
      {
        id: 'f-dz-01',
        category: 'seo',
        severity: 'good',
        title: 'HTTPS & Mobile Responsive Viewport Detected',
        evidence: 'SSL active and mobile viewport meta tag configured.',
        explanation: 'Essential for mobile-first indexing in Pakistan.',
        solution: 'Maintain fast mobile page speed.',
      },
      {
        id: 'f-dz-02',
        category: 'aeo',
        severity: 'warning',
        title: 'Missing FAQ Schema on Help Center Articles',
        evidence: 'Help center contains Q&A text but lacks JSON-LD FAQPage markup.',
        explanation: 'Limits voice search citations for Pakistani delivery queries.',
        solution: 'Add FAQPage JSON-LD schema on customer care pages.',
      },
    ],
    urlReports: [
      {
        id: 'rep-dz-home',
        url: 'https://www.daraz.pk',
        path: '/',
        title: 'Online Shopping in Pakistan: Fashion, Electronics & Grocery – Daraz.pk',
        metaDescription: 'Daraz.pk is the leading online shopping platform in Pakistan. Shop electronics, fashion, home appliances, groceries and get fast delivery across Pakistan.',
        canonicalUrl: 'https://www.daraz.pk/',
        robots: 'index, follow',
        statusCode: 200,
        responseTimeMs: 180,
        wordCount: 2100,
        readingTimeMinutes: 10,
        internalLinksCount: 240,
        externalLinksCount: 15,
        imagesCount: 35,
        imagesWithoutAlt: 2,
        headings: {
          h1: ['Online Shopping in Pakistan at Daraz.pk'],
          h2: ['Flash Sale', 'Categories', 'Just For You', 'Daraz Mall'],
          h3: ['Mobile Phones & Accessories', 'Electronics & Appliances', 'Fashion & Beauty'],
        },
        schemaTypes: ['Organization', 'WebSite', 'ItemPage'],
        openGraph: {
          'og:title': 'Daraz Pakistan Online Shopping',
          'og:description': 'Shop online in Pakistan with cash on delivery.',
        },
        twitterCard: { 'twitter:card': 'summary_large_image' },
        scores: { seo: 92, aeo: 85, aio: 88, geo: 83, eeat: 91, overall: 88 },
        findings: [
          {
            id: 'f-dz-good',
            category: 'seo',
            severity: 'good',
            title: 'High Regional Keyword Relevance',
            evidence: 'Targets high-intent Pakistani search queries effectively.',
            explanation: 'Drives organic traffic across Pakistan.',
            solution: 'Optimize category titles for emerging search trends.',
          },
        ],
        aiRecommendations: [
          'Add alt tags to 2 missing banner images.',
          'Implement bilingual (Urdu/English) FAQ schema on buyer protection pages.',
        ],
        crawledAt: new Date(Date.now() - 3600000 * 48).toISOString(),
      },
    ],
  },
];
